version: "3.9"
services:

  db:
    image: mysql:latest
    restart: always
    container_name: usuarios
    environment:
      MYSQL_DATABASE : "usuarios"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "jsaire"
      MYSQL_PASSWORD: "secret"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"